export const MAX_CONNECTED_SORTERS = 3;

export const DEVICE_NAME_MAX_LENGTH = 50;

export const STORAGE_LOCATION_NAME_MAX_LENGTH = 50;
export const STORAGE_SEARCH_RESULT_LIMIT = 100;
export const STORAGE_SEARCH_QUERY_MAX_LENGTH = 100;

export const CHAOS_BIN_SIZE_MAX = 10_000;
